version: '3.1'

services:
  db:
    container_name: climate-map-db
    build: ./postgres
    restart: always
    env_file:
        - ./.env
    ports:
        - "${POSTGRES_PORT}:5432"
    volumes:
        - ./postgres/database:/var/lib/postgresql:z
        - sql_scripts:/sql_scripts:z

  node:
    container_name: climate-map-node
    depends_on:
        - db
    build: ./src
    restart: always
    env_file:
        - ./.env
    ports:
        - "${NODE_PORT}:8080"
    volumes:
        - ./src/:/home/node/app:z
        - ./data:/data:z
        - sql_scripts:/sql_scripts:z

volumes:
    sql_scripts:

